# .streamlit/secrets.toml

# MinIO / S3 storage config
[minio]
MINIO_ENDPOINT = "http://minio:9000"
MINIO_ACCESS_KEY = "admin"
MINIO_SECRET_KEY = "admin123"
MINIO_BUCKET = "gold"
BUCKET = "silver"


# Database config
[database]
host = "//host.docker.internal:1433"
port = "1433"
dbname = "HospitalManagementSystem"
user = "testuser"
password = "240325@Strong!"

# Optional: add other secrets here
[api]
openai_key = "YOUR_OPENAI_API_KEY"
